definitions:
  identity-service_identity_dataMapper_v1_http.Attribute:
    properties:
      attribute_value:
        type: string
      is_verified:
        type: boolean
    type: object
  identity-service_identity_dataMapper_v1_http.Policy:
    properties:
      attributes_list:
        items:
          type: string
        type: array
      operator_type:
        type: string
      policy_type:
        type: string
    type: object
  v1.Attributes:
    properties:
      aadhaar:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
      email:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
      employee_code:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
      gst:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
      gst_location:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
      pan:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
      phone:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Attribute'
    type: object
  v1.IdentityRequestPayload:
    properties:
      attributes:
        $ref: '#/definitions/v1.Attributes'
      policy:
        $ref: '#/definitions/identity-service_identity_dataMapper_v1_http.Policy'
      user_id:
        type: integer
      user_type:
        type: string
    type: object
  v1.IdentityResponsePayload:
    properties:
      conflict_reason:
        type: string
      gid:
        type: string
      remark:
        type: string
    type: object
  v1.IdentityUpdateRequestPayload:
    properties:
      attributes:
        $ref: '#/definitions/v1.Attributes'
      gid:
        type: string
    type: object
  v1.IdentityUpdateResponsePayload:
    properties:
      remarks:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: Identity Service Apis.
  title: Identity Services API
  version: "1.0"
paths:
  /create-identity/v1:
    post:
      consumes:
      - application/json
      description: Create a new identity.
      parameters:
      - description: Identity request payload
        in: body
        name: IdentityRequestPayload
        required: true
        schema:
          $ref: '#/definitions/v1.IdentityRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created identity
          schema:
            $ref: '#/definitions/v1.IdentityResponsePayload'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerToken: []
      summary: Create Identity
      tags:
      - Identity
  /update-identity/v1:
    post:
      consumes:
      - application/json
      description: Update an existing identity.
      parameters:
      - description: Identity update request payload
        in: body
        name: IdentityUpdateRequestPayload
        required: true
        schema:
          $ref: '#/definitions/v1.IdentityUpdateRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated identity
          schema:
            $ref: '#/definitions/v1.IdentityUpdateResponsePayload'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerToken: []
      summary: Update Identity
      tags:
      - Identity
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
